package jp.co.yumemi.android.code_check.data.database.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
/**
 * Data class representing a search history entry.
 *
 * @property id The unique identifier of the search history entry. Automatically generated by Room.
 * @property query The search query text.
 * @property timestamp The timestamp when the search was performed.
 */
@Entity(tableName = "search_history")
data class SearchHistory(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "query") val query: String,
    @ColumnInfo(name = "timestamp") val timestamp: String
)